version: '2'

services:
  mercury-mysql:
    image: mysql:5.7
    container_name: mercury-mysql
    restart: always
    ports:
      - '13306:3306'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${MYSQL_TIMEZONE}
    volumes:
      - mercury-mysql-data:/var/lib/mysql
      #      - ./my-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./set-grant-permission-to-user.sql:/docker-entrypoint-initdb.d/set-grant-permission-to-user.sql
    networks:
      - mercury-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=${MYSQl_CHARSET} --collation-server=${MYSQl_COLLATION}

  mercury-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mercury-phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mercury-mysql
    networks:
      - mercury-network

volumes:
  mercury-mysql-data:
    driver: local

networks:
  mercury-network:
    external: true